# Generated by Django 4.2.8 on 2025-05-30 16:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='projetos_membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projeto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core.projeto')),
            ],
            options={
                'db_table': 'board',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('limite_wip', models.IntegerField(default=0, help_text='Work In Progress - 0 = sem limite')),
                ('cor', models.CharField(default='#6B7280', max_length=7)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='core.board')),
            ],
            options={
                'db_table': 'coluna',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', '🟢 Baixa'), ('media', '🟡 Média'), ('alta', '🟠 Alta'), ('critica', '🔴 Crítica')], default='media', max_length=10)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('arquivado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa - Cosmético'), ('media', 'Média - Funcional menor'), ('alta', 'Alta - Funcional maior'), ('critica', 'Crítica - Sistema parado')], default='media', max_length=10)),
                ('ambiente', models.CharField(default='produção', help_text='Ex: produção, homologação, desenvolvimento', max_length=50)),
                ('passos_reproducao', models.TextField(blank=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_items', to='core.coluna')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bug_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug',
                'ordering': ['-prioridade', '-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', '🟢 Baixa'), ('media', '🟡 Média'), ('alta', '🟠 Alta'), ('critica', '🔴 Crítica')], default='media', max_length=10)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('arquivado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('ux', 'UX/UI'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('infra', 'Infraestrutura'), ('docs', 'Documentação')], default='backend', max_length=20)),
                ('estimativa_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('especificacao_url', models.URLField(blank=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='core.coluna')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature',
                'ordering': ['-prioridade', '-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_hora', to='core.bug')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_hora', to='core.feature')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_hora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_hora',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.bug')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.feature')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comentario',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='coluna',
            constraint=models.UniqueConstraint(fields=('board', 'ordem'), name='core_coluna_board_id_ordem_uniq'),
        ),
    ]